name: MammaMia
version: 1.1
main: com.thegameratort.mammamia.MammaMia
api-version: 1.16
authors: [ TheGameratorT ]
description: The Mamma Mia server controller plugin.
depend: [ Multiverse-Core, Multiverse-Inventories, FastAsyncWorldEdit ]

commands:
  mammamia:
    description: Generic MammaMia Command
    usage: /<command>
  track:
    description: Generic MammaMia Command
    usage: /<command>
  discord:
    description: Generic MammaMia Command
    usage: /<command>
  manhunt:
    description: Generic MammaMia Command
    usage: /<command>
  kit:
    description: Generic MammaMia Command
    usage: /<command>
  pvp:
    description: Generic MammaMia Command
    usage: /<command>
